---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pothouse-ingress
spec:
  rules:
  - http:
      paths:
      - path: /auth
        backend:
          serviceName: yifans-auth-service
          servicePort: 9080
